name: gallery_app
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  url_strategy: ^0.3.0
  auto_route: ^9.2.2
  auto_route_generator: ^9.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.2.2

dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
